[tool.pytest.ini_options]
# Путь к директории с тестами
testpaths = "tests"

# Включение дополнительных плагинов и опций
addopts = "-v -s -l"
# -v: Включает подробный вывод (verbose mode), который показывает больше информации о выполнении тестов.
# -l: Показывает локальные переменные в трассировке стека при сбое теста.
# -s: Выводит в консоль все текста из функции 'print' если такие есть в тексте